networks:
  172.16.20.0/24:
    devices:
      - type: switch
        name: sw1
      - type: switch
        name: sw2
      - type: streaming
        mac: B0:EE:7B:CE:87:66
        manufacturer: roku
      - type: printer
        name: printer-office-1
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        name: printer-office-2
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        mac: 38:9d:92
        name: printer-office-3
        manufacturer: 'Epson'
        model: 'WorkForce Enterprise WF-C21000'
      - type: streaming
        mac: B0:EE:7B:FF:9F:F0
        manufacturer: roku
      - type: phone
        name: frontdesk-voip
      - type: phone
        name: conference-voip
      - type: phone
        name: warehouse-1-voip
      - type: phone
        name: warehouse-2-voip
      - type: phone
        name: office-1-voip
      - type: phone
        name: office-2-voip
      - type: phone
        name: office-3-voip
