networks:
  172.16.20.0/24:
    devices:
      - type: switch
        name: SW-RM100
      - type: switch
        name: SW-RM200
      - type: nas
        name: NAS-01
      - type: streaming
        mac: B0:EE:7B:32:31:98
        name: SCREENSHARE-1
        manufacturer: roku
      - type: streaming
        mac: B0:EE:7B:34:75:5C
        name: SCREENSHARE-2
        manufacturer: roku
      - type: printer
        mac: 9C:93:4E:D0:C8:E0
        name: MFP-RM203
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        mac: 00:00:AA:FA:8C:57
        name: MFP-RM104
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        mac: 00:00:01:24:6F:49
        name: MFP-RM227
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        mac: 00:00:04:1B:45:73
        name: MFP-RM100
        manufacturer: 'Xerox'
        model: 'PRIMELINK C9065/C9070'
      - type: printer
        mac: 38:9D:92:62:89:F0
        name: MFP-FrontOffice
        manufacturer: 'Epson'
        model: 'WorkForce Enterprise WF-C21000'
      - type: phone
        mac: 00:03:6b
        name: VOIP-RM111
      - type: phone
        mac: 00:01:e3
        name: VOIP-RM112
      - type: phone
        mac: 00:04:0d
        name: VOIP-RM113
      - type: phone
        mac: 00:e0:75
        name: VOIP-RM114
      - type: phone
        mac: 00:60:38
        name: VOIP-RM115
      - type: phone
        mac: 00:04:F2
        name: VOIP-CONF-1
      - type: phone
        mac: 00:E0:BB
        name: VOIP-CONF-2
      - type: phone
        mac: 00:08:5D
        name: VOIP-FRONTOFFICE